/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bots: typeof import('./src/components/Bots.vue')['default']
    Categories: typeof import('./src/components/Categories.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Integrations: typeof import('./src/components/Integrations.vue')['default']
    ItemsLoader: typeof import('./src/components/common/ItemsLoader.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NavigateHeader: typeof import('./src/components/common/NavigateHeader.vue')['default']
    Orders: typeof import('./src/components/Orders.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    Promotions: typeof import('./src/components/Promotions.vue')['default']
    Registration: typeof import('./src/components/Registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scenarios: typeof import('./src/components/Scenarios.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Shippings: typeof import('./src/components/Shippings.vue')['default']
  }
}
